export default [
  {
    name: 'Ahnaf Ahmed',
    position: 'President',
    major: 'Electrical Engineering',
    minor: 'Business',
    depth: 'Intelligent Systems, Robotics & Controls',
    lines: [
      'Employed at Cubic Global Defense',
      'Enjoys Basketball, weight lifting, hiking',
      '"I\'m ambidextrous"',
    ],
    isExec: true,
    pic: 'pics/18-19/ahnaf.jpg',
    email: "bvb112Avdte/fev",
  },
  {
    name: 'Jasmine Chiang',
    position: 'VP External',
    major: 'Electrical Engineering',
    minor: null,
    depth: 'Signal and Image Processing',
    lines: [
      'Also a part of Scholars Society',
      'Senior Peer Facilitator at Summer Engineering Institute',
      'Enjoys comedic stand up',
    ],
    isExec: true,
    pic: 'pics/18-19/jasmine.jpg',
    email: "kzd1:9Avdte/fev",
  },
  {
    name: 'Victor Miranda',
    position: 'VP Internal',
    major: 'Electrical Engineering',
    minor: null,
    depth: 'Machine Learning',
    lines: [
      'Also a part of Lambda Theta Phi',
      'Lead Tutor of ECE 5',
      'Enjoys his penny board, rap, hiking',
      '"I used to eat nutella sandwiches with ham"',
    ],
    isExec: true,
    pic: 'pics/18-19/victor.jpg',
    email: "WNjsboebAvdte/fev",
  },
  {
    name: 'Bassel Hatoum',
    position: 'Secretary',
    major: 'Electrical Engineering',
    minor: null,
    depth: 'Machine Learning and Controls',
    lines: [
      'Also a part of IEEE (Project Space Chair)',
      'Enjoys movies, soccer, basketball, food',
      '"I\'ve lived in 5 different countries"',
    ],
    pic: 'pics/18-19/bassel.jpg',
    email: "cibupvnAvdte/fev",
  },
  {
    name: 'Shivani Bhakta',
    position: 'Treasurer',
    major: 'Electrical Engineering',
    minor: null,
    depth: null,
    lines: [
      'Also a part of PiB and IEEE',
      'Enjoys reading (literally anything)',
    ],
    pic: 'pics/18-19/shivani.jpg',
    email: "t:ciblubAvdte/fev",
  },
  {
    name: 'Bryant Liu',
    position: 'Mentorship Chair',
    major: 'Computer Engineering',
    minor: null,
    depth: null,
    lines: [
      'Electro-Optics Lab Assistant at CLEARink Displays ',
      'Enjoys Photography, web development, biking',
      '"I drink a lot of caffiene"',
    ],
    pic: 'pics/18-19/bryant.jpg',
    email: "csm183Avdte/fev",
  },
  {
    name: 'Arden Ma',
    position: 'Outreach Chair',
    major: 'Electrical Engineering',
    minor: null,
    depth: 'Machine Learning and Controls',
    lines: [
      'Also a part of IEEE',
      'Involved in SRIP 2018',
      'Enjoys swimming, surfing, programming',
      'Hiked Half Dome ince',
    ],
    pic: 'pics/18-19/arden.jpg',
    email: "bxnbAvdte/fev",
  },
  {
    name: 'Po Hsiang Huang',
    position: 'Events Coordinator',
    major: 'Electrical Engineering',
    minor: null,
    depth: 'Machine Learning and Controls',
    lines: [
      'Employed at Teaching and Learning Commons in Geisel',
      'Enjoys Guitar, many sports, food, sleep',
      '"The name I go by is the same as Kungfu Panda and the red Teletubby"',
    ],
    pic: 'pics/18-19/po.jpg',
    email: "qii114Avdte/fev",
  },
  {
    name: 'Kelsey Haughan',
    position: 'Publicity Chair',
    major: 'Electrical Engineering',
    minor: null,
    depth: 'Circuit and Systems',
    lines: [
      'Also a part of Kappa Alpha Theta',
      'Employed at Ametek Programmable Power, SoulCycle',
      'Enjoys soccer, indoor cycling, plannering, food',
      '"Couldn\'t snap until I was 14 ):"',
    ],
    pic: 'pics/18-19/kelsey.png',
    email: "libvhiboAvdte/fev",
  },
  {
    name: 'Chau Vu',
    position: 'Committee Liaison',
    major: 'Computer Engineering',
    minor: null,
    depth: null,
    lines: [
      'Also a part of CSE ESRP',
      'Employed at Code To The Future',
      'Enjoys Board games, Taekwondo',
      '"If you don\'t like pineapple on pizza, we can\'t be friends."',
    ],
    pic: 'pics/18-19/chau.jpg',
    email: "diw115Avdte/fev",
  },
  {
    name: 'Hassan Eid',
    position: 'Committee Liaison',
    major: 'Electrical Engineering',
    minor: null,
    depth: null,
    lines: [
      'Also a part of PiB R&D',
      'Employed at UCSD IT Services',
      'Enjoys Football, Graphic Design, Movies',
      '"I studied abroad in Paris"',
    ],
    pic: 'pics/18-19/hassan.jpg',
    email: "infjeAvdte/fev",
  },
]
