export default [
  {
    name: 'Ahnaf Ahmed',
    position: 'President',
    major: 'Electrical Engineering',
    minor: 'Business',
    depth: 'DSP',
    lines: [],
    isExec: true,
    pic: 'pics/18-19/ahnaf.png',
  },
  {
    name: 'Jasmine Chiang',
    position: 'VP External',
    major: 'Electrical Engineering',
    minor: null,
    depth: null,
    lines: [],
    isExec: true,
    pic: 'pics/18-19/jasmine.jpeg',
  },
  {
    name: 'Victor Miranda',
    position: 'VP Internal',
    major: 'Electrical Engineering',
    minor: null,
    depth: null,
    lines: [],
    isExec: true,
    pic: 'pics/18-19/victor.jpeg',
  },
  {
    name: 'Bassel Hatoum',
    position: 'Secretary',
    major: 'Electrical Engineering',
    minor: null,
    depth: null,
    lines: [],
    pic: 'pics/18-19/bassel.png',
  },
  {
    name: 'Shivani Bhakta',
    position: 'Treasurer',
    major: 'Electrical Engineering',
    minor: null,
    depth: null,
    lines: [],
    pic: 'pics/18-19/shivani.png',
  },
  {
    name: 'Bryant Liu',
    position: 'Mentorship Chair',
    major: 'Computer Engineering',
    minor: null,
    depth: null,
    lines: [],
    pic: 'pics/18-19/bryant.png',
  },
  {
    name: 'Arden Ma',
    position: 'Outreach Chair',
    major: 'Electrical Engineering',
    minor: null,
    depth: null,
    lines: [],
    pic: 'pics/18-19/arden.jpeg',
  },
  {
    name: 'Po Hsiang Huang',
    position: 'Events Coordinator',
    major: 'Electrical Engineering',
    minor: null,
    depth: null,
    lines: [],
    pic: 'pics/18-19/po.png',
  },
  {
    name: 'Kelsey Haughan',
    position: 'Publicity Chair',
    major: 'Electrical Engineering',
    minor: null,
    depth: null,
    lines: [],
    pic: 'pics/18-19/kelsey.png',
  },
  {
    name: 'Chau Vu',
    position: 'Committee Liason',
    major: 'Computer Engineering',
    minor: null,
    depth: null,
    lines: [],
    pic: 'pics/18-19/chau.jpeg',
  },
  {
    name: 'Hassan Eid',
    position: 'Committee Liason',
    major: 'Electrical Engineering',
    minor: null,
    depth: null,
    lines: [],
    pic: 'pics/18-19/hassan.jpeg',
  },
]