name: Deploy to eceusc.ucsd.edu

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - run: npm install 
    - run: npm run build
    - run: ls -lah  
    - uses: os-ucsd/actions/acsweb@0.1.0
      with:
        username: eceusc
        password: "${{secrets.ACSWEB_PASSWORD}}"
        local_dir: "./build/"
    - uses: rtCamp/action-slack-notify@v1.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: website
        SLACK_MESSAGE:  "The site has been updated  by ${{ github.actor }} with a Github Action! :rocket: "
